apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.namespace }}-dummy-vuln-app
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-0c39130539688f31e
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Values.namespace }}-dummy-vuln-app
              servicePort: 80
